name: Build a firmware on demand

on:
  workflow_dispatch:
    inputs:
      keyboard:
        description: 'Keyboard'
        required: true
        type: choice
        # QMK 0.34.6 に移植したのは keyball39 だけ (build-all.yml を参照)
        options:
        - keyball39
      keymap:
        description: 'Keymap'
        required: true
        type: string
        default: 'default'

jobs:

  build:

    uses: ./.github/workflows/build-firmware.yml
    with:
      qmk_version: '0.34.6'
      keyboard:    ${{ inputs.keyboard }}
      keymap:      ${{ inputs.keymap }}
